OpenRA/OpenRAModSDK

.gitignore, .gitmodules, Makefile, fetch-engine.sh, launch-dedicated.cmd, launch-dedicated.sh, launch-game.cmd, launch-game.sh, make.ps1, mod.config, mods/example/mod.yaml, utility.cmd, utility.sh
Closes #7.
I would like to get a second/third set of eyes on this before merging – especially the Linux/macOS scripts, which I have reworked from the first version to follow the more sensible approach of @abcdefg30's powershell scripts.
=> Automatically manage engine versions

Makefile
Fixes #25 by avoiding hard-coded directory names.
Note: I have only tested this on macOS.  It needs to be tested on a Linux system (case sensitive FS, gnu coreutils) before merging.
=> Style check all csproj dirs from the makefile.

.travis.yml, packaging/osx/buildpackage.sh
This is to avoid confusion with the .zip package from https://github.com/OpenRA/OpenRAModSDK/pull/61.
=> Rename .zip package for osx

mod.config, packaging/linux/include/AppRun.in, packaging/linux/include/mod.desktop.in, packaging/linux/include/mod.in
This PR backports the improvements from https://github.com/OpenRA/OpenRA/pull/15086:
- Improved crash dialogs (including KDE support)
- Distinguish WMStartupClass using versions
- Refresh the icon cache on first run
They have already been reviewed upstream, so merging immediately.
=> Port upstream AppImage improvements.

mod.config
Counterpart to https://github.com/OpenRA/OpenRA/pull/15379.
=> Update macOS launcher template to osx-launcher-20180723.

launch-dedicated.cmd, launch-dedicated.sh, packaging/linux/buildpackage.sh, packaging/osx/buildpackage.sh, packaging/windows/buildpackage.sh
We already removed `ExternalPort` upstream.
Also removes trailing tabs from the `buildpackage.sh` scripts.
=> Remove all uses of ExternalPort

fetch-engine.sh, packaging/linux/buildpackage.sh, packaging/osx/buildpackage.sh, packaging/package-all.sh, packaging/windows/buildpackage.sh
Hi,
This pull request is really just a follow up of OpenRA/OpenRA#15351, wherein I add wget support to the Linux-centric scripts for fetching and building. I did wonder whether I should also add support to the [package-all.sh](https://github.com/OpenRA/OpenRAModSDK/blob/master/packaging/package-all.sh), [osx buildpackage.sh](https://github.com/OpenRA/OpenRAModSDK/blob/master/packaging/osx/buildpackage.sh) and [windows buildpackage.sh](https://github.com/OpenRA/OpenRAModSDK/blob/master/packaging/windows/buildpackage.sh) scripts for wget, but they're mostly just used by the project's Travis CI instance so I do not think that's really necessary. Although if you's believe I should I will be happy to. If I do, however, I should probably also do so for the main project, …
=> Adding wget support to Linux fetch and build scripts.

.travis.yml, Makefile
Fixes #97.
Testcase 1: `unix2dos mod.config && make`
Testcase 2: `chmod a-x launch-game.sh && make`
=> Add makefile checks for common errors introduced by windows-only developers

.travis.yml
http://www.yamllint.com/ suggested the `:` is the issue. Escaping it using `\` did not work.
=> Try to fix travis not parsing .travis.yml

mod.config
Counterpart to https://github.com/OpenRA/OpenRA/pull/15635.
Reverts #91.
=> Revert macOS dark mode support.

packaging/windows/buildpackage.sh
=> Explicitly include the zip extension in the windows packaging.

.travis.yml, ExampleMod.sln, Makefile, OpenRA.Mods.Example/OpenRA.Mods.Example.csproj, make.ps1, mod.config, mods/example/mod.yaml, mods/example/rules.yaml, packaging/linux/buildpackage.sh, packaging/linux/include/AppRun.in, packaging/linux/include/Eluant.dll.config, packaging/linux/include/OpenAL-CS.dll.config, packaging/linux/include/SDL2-CS.dll.config, packaging/linux/include/mod-utility.in, packaging/osx/buildpackage.sh, packaging/windows/buildpackage.nsi, packaging/windows/buildpackage.sh
This changes the SDK to account for:
* https://github.com/OpenRA/OpenRA/pull/16316
* https://github.com/OpenRA/OpenRA/pull/16319
* https://github.com/OpenRA/OpenRA/pull/16345
* https://github.com/OpenRA/OpenRA/pull/16451
* https://github.com/OpenRA/OpenRA/pull/16506
* https://github.com/OpenRA/OpenRA/pull/16516
* https://github.com/OpenRA/OpenRA/pull/16529
* https://github.com/OpenRA/OpenRA/pull/16537
* https://github.com/OpenRA/OpenRA/pull/16580
Fixes #113.
This depends on changes that have not yet been merged upstream, and will break compatibility with the current stable release. I'll keep this as a draft until we are ready to push the next playtest.
* Updated engine to `playtest-20190825`
* Updated toolchain to work with the new OpenRA engine
* Linux and macOS applications no longer …
=> Update scripts to work with the new engine toolchain.

make.ps1
It would report `Deleting engine version .` otherwise.
Note that this (deliberately) changes the script behaviour to disallow using an empty engine version string (in `mod.config`).
=> Fix $currentEngine never being initialised

.travis.yml, mod.config
Fixes #118.
Fixes #125.
Updates engine version to playtest-20191021.
=> Packaging fixes for playtest-20191021

packaging/windows/buildpackage.nsi
Noticed that this is still there while updating RA Classic to playtest-20200303. The file doesn't exist in the playtest anymore and causes travis to fail while creating the windows installer. Removing it made travis pass properly.
=> Remove GeoLite2-Country.mmdb.gz from Windows Packaging Script

launch-dedicated.cmd, launch-dedicated.sh, mod.config, packaging/windows/buildpackage.nsi
This PR bumps the engine version and adds compatibility for https://github.com/OpenRA/OpenRA/pull/17930.
Once this has been merged we can tag a new `20200418` release with notes:
<hr>
* Update engine reference for OpenRA playtest-20200418.
* Updated launch-dedicated and windows packaging for compatibility with playtest-20200418.
* Fixed an error relating to the engine VERSION file when updating a mod under Windows.
This is a minor update. The following files have changed:
* `launch-dedicated.cmd`
* `launch-dedicated.sh`
* `make.cmd`
* `packaging/windows/buildpackage.nsi`
To update from the `20200329` SDK release simply copy the new versions of `launch-dedicated.cmd`, `launch-dedicated.sh`, `make.cmd`, `packaging/windows/buildpackage.nsi` into your mod project and change `ENGINE_VERSION` …
=> Update for playtest-20200418

launch-dedicated.sh, mod.config
Ready to tag a new SDK release.
* Fix launch-dedicated.sh failing to detect the server files.
* Update engine reference for OpenRA release-20210321.
This is a minor update to target the latest engine version. The following files have changed:
* `launch-dedicated.sh`
* `mod.config`
Please see the notes for the [20210131](https://github.com/OpenRA/OpenRAModSDK/releases/tag/20210131) releases for instructions on how to update from earlier engine versions.
=> Update to release-20210321

packaging/windows/buildpackage.nsi
On Windows, uninstalling the 64-bit version of an OpenRA mod leaves the registry entries behind. This leaves an entry in the Add/Remove Programs list which can't be removed unless you registry hack.
The fix was to call SetRegView 64 when uninstalling to specify the 64-bit registry. I tested both the 64 bit and 32 bit uninstall and they both function correctly and remove the registry entries OK.
=> Fix for Windows uninstaller to remove reg entries from the 64 bit registry

.vscode/extensions.json, Makefile, OpenRA.Mods.Example/Widgets/Logic/TemplateMenuLogic.cs, mod.config, packaging/functions.sh, packaging/windows/buildpackage.nsi, utility.cmd
#180 was merged before it was ready, so this continues its work. Hopefully these will be the last changes needed to update the ModSDK to match the upcoming OpenRA release, with only the target engine version left to update once there is a final OpenRA release.
=> Finish updating to release-20230225

.vscode/launch.json, OpenRA.Mods.Example/Properties/launchSettings.json
Over the last release cycle we added a bunch of tools to help launch and debug mods, mostly via VSCode and the missing piece was VS.
This is taken from the D2 mod and was added by @evgeniysergeev.
=> Added launchSettings.json for launching via VS
