OpenRA/OpenRAModSDK

launch-dedicated.sh, launch-game.sh, utility.sh
Tested using http://www.shellcheck.net/.
Tested on macOS and Ubuntu 17.04.
=> Fix posix compatibility and code style of shell scripts.

Makefile, OpenRA.Mods.Example/OpenRA.Mods.Example.csproj
=> Add a Makefile

make.ps1
`OpenRA.StyleCheck.exe` is now used.
=> Update make check for windows

COPYING
=> Add GPLv3 COPYING file

Makefile
=> Parse user.config from the makefile.

Makefile
=> Build system: Do not print success message if building fails

packaging/linux/buildpackage.sh, packaging/linux/include/AppRun.in, packaging/linux/include/gtk-dialog.py, packaging/linux/include/mod.in
This PR incorporates the changes from https://github.com/OpenRA/OpenRA/pull/15291, https://github.com/OpenRA/OpenRA/pull/15299, and https://github.com/OpenRA/OpenRA/pull/15316.
=> Port AppImage improvements from upstream.

packaging/linux/include/gtk-dialog.py
Discovered in https://github.com/OpenRA/OpenRAModSDK/pull/86#pullrequestreview-134690461.
=> Fix the mode documentation in gtk-dialog.py

packaging/linux/include/AppRun.in
Counterpart to https://github.com/OpenRA/OpenRA/pull/15496.
=> Add a hard requirement on the cert-sync utility.

OpenRA.Mods.Example/OpenRA.Mods.Example.csproj
Counterpart to https://github.com/OpenRA/OpenRA/pull/15553.
=> Fix compiler warnings on linux

packaging/windows/buildpackage.sh
=> Add workaround for untrusted exes on Windows.

packaging/windows/buildpackage.sh
To bring it in line with the rest of the file(s).
=> Change spaces to tabs in packaging/windows/buildpackage.sh

.travis.yml, Makefile
=> Check packaging scripts are executable before running them.

packaging/linux/buildpackage.sh, packaging/linux/include/AppRun.in, packaging/linux/include/mod-utility.in
Counterpart to https://github.com/OpenRA/OpenRA/pull/15894.
=> Add a --utility argument to the AppImage.

.editorconfig
The file is identical to the one in the OpenRA repository.
Closes #116
=> Added an .editorconfig file to the repository

mods/example/tileset.yaml
See https://github.com/OpenRA/OpenRA/pull/13339 as the definitions will crash newbies multiple times when building a mod from the ground upward.
=> Fix / update the tileset definitions

.travis.yml
=> Fix the travis error message when CRs are present in mod.config

mods/example/mod.yaml
=> Fix sound and notification references.

Makefile
Closes https://github.com/OpenRA/OpenRAModSDK/issues/128.
=> Fixed the build when there is no Visual Studio Solution File

make.ps1
The Windows/Powershell counterpart to #134.
=> Fix make errors when there is no custom solution file

mod.config
=> Update macOS support files to the latest version.

mod.config
=> Update to playtest-20200329

make.ps1
Fixes #66, as confirmed by ELoyros on Discord.
=> Make sure the engine VERSION file has been closed before continuing.

launch-game.sh
Same as https://github.com/OpenRA/OpenRA/pull/18375.
=> Add a check for Python 3 on Ubuntu and derivates

make.ps1
Backport of https://github.com/OpenRA/ra2/pull/734 which was a confirmed fix for https://github.com/OpenRA/ra2/issues/732#issuecomment-638142007.
=> Set the working directory for Powershell IO methods

.vscode/extensions.json, .vscode/launch.json, .vscode/tasks.json
to match @OpenRA and to resolve common problems like tabs vs spaces (via @EditorConfig)
=> Added Visual Studio Code metadata

make.ps1
Also add extra output for clarity.
Fixes #184.
=> Fix MOD_SEARCH_PATH in make.ps1

.editorconfig, launch-dedicated.sh
Fixes a regression introduced in https://github.com/OpenRA/OpenRAModSDK/pull/180.
=> Fixed Unix dedicated server launch script

.github/workflows/ci.yml, .github/workflows/packaging.yml, Makefile, make.ps1
This cherry-picks some changes from OpenRA/OpenRA that would be beneficial for the SDK even without a full release update.
=> Minor updates to the SDK
